name: Sonar-Workflow

on:
  push:
   branches: [ master, sonar.yml]
  pull_request:
    branches: [ master]
    types: [opened]  

jobs:
 sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONAR_HOST }}
        login: ${{ secrets.SONAR_KEY }}
        projectKey: Test-automation-sample
        projectName: Test-automation-sample
