name: Sonar-Workflow

on:
  push:
   branches: [ master, sonar.yml ]
  pull_request:
    branches: [ master]
    types: [opened]  

jobs:
 sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONAR_HOST }}
        login: ${{ secrets.SONAR_KEY }}
        projectKey: Test-automation-sample
        projectName: Test-automation-sample
        
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      
     
